{% set name = "google-api-core" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25d29e05a0058ed5f19c61c0a78b1b53adea4d9364b464d014fbda941f6d1c9a

build:
  number: 1
  noarch: python

outputs:
  - name: {{ name }}
    build:
      noarch: python
      script: python -m pip install . -vv --no-deps
    requirements:
      host:
        - python >=3.7
        - pip
      run:
        - python >=3.7
        - googleapis-common-protos >=1.56.2,<2.0.0
        - protobuf >=3.19.5,<5.0.0.0,!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5
        - google-auth >=2.14.1,<3.0.0
        - requests >=2.18.0,<3.0.0.0
    test:
      requires:
        - pip
      imports:
        - google.auth
        - google.auth.credentials
        - google.auth.transport.requests
        - google.longrunning
        - google.longrunning.operations_pb2
        - google.protobuf
        - google.rpc
        - google.api_core
        - google.api_core.exceptions
        - google.api_core.future
        - google.api_core.future.base
        - google.api_core.future.polling
        - google.api_core.general_helpers
        - google.api_core.page_iterator
        - google.api_core.protobuf_helpers
        - google.api_core.retry
        - google.api_core.timeout
      commands:
        - python -m pip check

  - name: {{ name }}-grpc
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage(name, exact=True) }}
        # upstream has tighter bounds on these for py3.11 but I don't think we
        # want to give up noarch for that
        - grpcio >=1.33.2,<2.0.0
        - grpcio-status >=1.33.2,<2.0.0
    test:
      requires:
        - pip
      imports:
        - google.api_core
      commands:
        - python -m pip check
    about:
      home: https://github.com/googleapis/python-api-core
      license: Apache-2.0
      license_family: APACHE
      summary: Core Library for Google Client Libraries with grpc

about:
  home: https://github.com/googleapis/python-api-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Core Library for Google Client Libraries
  description: |
    Core Library for Google Client Libraries
    -------------------------

    This package does not include the grpc, grpcio-gcp or grpcgcp extra requirements.

    This library is not meant to stand-alone. Instead it defines
    common helpers used by all Google API clients. For more information, see the
    [documentation](https://googleapis.dev/python/google-api-core/latest/index.html).

    Supported Python Versions
    -------------------------
    Python >= 3.5

    Deprecated Python Versions
    --------------------------
    Python == 2.7
    - Python 2.7 support will be removed on January 1, 2020.
    - protobuf does not support Visual C++ 2008, windows py27 package not available

  doc_url: https://googleapis.dev/python/google-api-core/latest/index.html
  dev_url: https://github.com/googleapis/python-api-core

extra:
  feedstock-name: google-api-core
  recipe-maintainers:
    - xylar
    - BrentDorsey
    - parthea
    - tpdownes
    - tswast
    - rxm7706
